Repository xmidt-org/caduceus, pull requests merged in 2020-05, with the labels that each got.

#205 updated shutdown function, also clear gauges on start and shutdown
  CHANGELOG.md
  outboundSender.go
Labels: bug

#209 removed queueEmpty variable from outbound sender
  CHANGELOG.md
  outboundSender.go
Labels: bug

#210 fixed dispatcher() on cutoff conditions
  CHANGELOG.md
  outboundSender.go
Labels: bug

#211 register for specific signals
  CHANGELOG.md
  main.go
Labels: enhancement

#219 made http retry codes configurable
  CHANGELOG.md
  caduceus.yaml
  caduceus_type.go
  main.go
  outboundSender.go
  outboundSender_test.go
  senderWrapper.go
Labels: bug

#217 made insecure TLS configurable
  CHANGELOG.md
  caduceus.yaml
  caduceus_type.go
  main.go
Labels: argus-webhooks, enhancement

#216 added metric to see how often caduceus is modifying the wrp
  CHANGELOG.md
  http.go
  http_test.go
  main.go
  metrics.go
Labels: enhancement
