Repository xmidt-org/caduceus, pull requests merged in 2024-10, with the labels that each got.

#557 chore: enable docker build and disable docker arm64 build
  .github/workflows/ci.yml
Labels: bug

#559 patch: remove anclaHelper.go
  caduceus.go
  go.mod
  go.sum
  internal/anclaHelper/anclaHelper.go
Labels: enhancement

#560 fix: move the execution instructions to the first line
  .release/docker/entrypoint.sh
Labels: bug

#561 chore: standardize dockerfile
  Dockerfile
Labels: bug

#562 chore: include docker-extras: `.release/docker`, `LICENSE`, `NOTICE`
  .github/workflows/ci.yml
Labels: bug

#556 Hashing Logic
  .gitignore
  cmd/caduceus/main.go
  internal/sink/hasher.go
  internal/sink/sink.go
Labels: caduceus-refactor
